### ISSUE TITLE
where is rpi_signal-cli.0.8.3.tar?

### ISSUE THREAD

**Issue by W11T** [DutchForeigner/signal-cli_rpi#3]
I can't find the tar file.
Anyway, i fetchted 0.8.1 a while ago. Good work!

**Comment by gcey** [comment]
I can't find any rpi_signal-cli.*.tar file as well :-(

**Comment by DutchForeigner** [comment]
Sorry, must have missed it when I uploaded the rest of the files. It is there now...

**Comment by gcey** [comment]
Many thanks, now I found it.
But it does not work (see https://github.com/DutchForeigner/signal-cli_rpi/issues/4).

**Comment by DutchForeigner** [comment]
Not sure what has gone wrong with the 0.8.3 build, as it was working on my rpi. Most likely I uploaded the wrong file...
Anyway, did not spend much time in finding the root cause. Instead have now compiled the latest version v0.8.4.1
Note that the tar and manual files are now in the 'Releases' section.

**Comment by W11T** [comment]
thank you!
