### ISSUE TITLE
v0.8.3 not working

### ISSUE THREAD

**Issue by W11T** [DutchForeigner/signal-cli_rpi#4]
rpi_signal-cli-0.8.3.tar fails:

OpenJDK Server VM warning: You have loaded library /tmp/resource2822273589915244810.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
WARN App - WARNING: Support for new group V2 is disabled, because the required native library dependency is missing: libzkgroup
Missing required native library dependency: libsignal-client

**Comment by gcey** [comment]
Unfortunately I'm getting the same error messages :-(

**Comment by DutchForeigner** [comment]
Not sure what has gone wrong with the 0.8.3 build, as it was working on my rpi. Most likely I uploaded the wrong file...
Anyway, did not spend much time in finding the root cause. Instead have now compiled the latest version v0.8.4.1
Note that the tar and manual files are now in the 'Releases' section.

**Comment by W11T** [comment]
great! 0.8.4.1 is working well!
Thank you!
